### ISSUE TITLE
Add hex number gen feature

### ISSUE THREAD

**Issue by Criomby** [Criomby/OpenPassword#8]

**Comment by Criomby** [comment]
@Criomby 
**TODO plan**

- [ ] create testing branch for feature
- [ ] how to integrate into existing JS class for password generation (PassGen)
- [ ] create first draft of feature
- [ ] frontend integration (3rd option for password type)

**Comment by Criomby** [comment]
![image](https://user-images.githubusercontent.com/86114549/200722053-8da96945-7809-48c9-8660-f9b0cabad511.png)

**Comment by Criomby** [comment]
![image](https://user-images.githubusercontent.com/86114549/200722319-8daf2094-64db-48e3-9787-770ef5b0cc0b.jpeg)

**Comment by Criomby** [comment]
![image](https://user-images.githubusercontent.com/86114549/200732549-7409bf41-1657-4c15-91ac-2d71634935ba.jpeg)
